site_name: Sabanci University Information Technology Master Degree
site_url: https://theomerkaratas.github.io/sabanci-university-information-technology-master-degree/
site_description: Sabancı University Master of Science in Information Technology Coursework and Projects
repo_name: theomerkaratas/sabanci-university-information-technology-master-degree
repo_url: https://github.com/theomerkaratas/sabanci-university-information-technology-master-degree
theme:
  name: material
  palette:
    # Sade ve sadece Dark Mode
    scheme: slate
    primary: black
    accent: black
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
