site_name: Sabanci University Information Technology Master Degree
site_url: https://theomerkaratas.github.io/sabanci-university-information-technology-master-degree/
site_description: Sabancı University Master of Science in Information Technology Coursework and Projects
repo_name: theomerkaratas/sabanci-university-information-technology-master-degree
repo_url: https://github.com/theomerkaratas/sabanci-university-information-technology-master-degree

google_analytics:
  - !!python/object/apply:os.getenv ["WORKFLOW_GOOGLE_ANALYTICS_KEY", "none"]
  - auto

plugins:
  - search:
      lang:
        - en

copyright: Copyright &copy; 2026 Ömer Karataş

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - toc.integrate

nav:
  - Introduction: index.md
  - IT501: IT501/README.md
  - IT511:
      - Main: IT511/README.md
      - Lecture Notes: IT511/Notes/LectureNotes/README.md
  - IT524:
      - Main: IT524/README.md
      - Lecture Notes: IT524/LectureNotes/README.md
  - IT526:
      - Main: IT526/README.md
      - Lecture Notes: IT526/LectureNotes/README.md
  - IT537: IT537/README.md
  - IT553: IT553/README.md
  - IT563: IT563/README.md
  - SEC509:
      - Main: SEC509/README.md
      - Chapters:
          - Chapter 1: SEC509/Documents/chapter1.md
          - Chapter 2: SEC509/Documents/chapter2.md
