version: '3.8'

services:
  practice-1:
    build: .
    ports:
      - "8001:80"
    volumes:
      - ./practice-1:/usr/share/nginx/html
    container_name: practice-1

  practice-2:
    build: .
    ports:
      - "8002:80"
    volumes:
      - ./practice-2:/usr/share/nginx/html
    container_name: practice-2

  practice-3:
    build: .
    ports:
      - "8003:80"
    volumes:
      - ./practice-3:/usr/share/nginx/html
    container_name: practice-3

  practice-4:
    build: .
    ports:
      - "8004:80"
    volumes:
      - ./practice-4:/usr/share/nginx/html
    container_name: practice-4

  practice-5:
    build: .
    ports:
      - "8005:80"
    volumes:
      - ./practice-5:/usr/share/nginx/html
    container_name: practice-5

  practice-6:
    build: .
    ports:
      - "8006:80"
    volumes:
      - ./practice-6:/usr/share/nginx/html
    container_name: practice-6

  practice-7:
    build: .
    ports:
      - "8007:80"
    volumes:
      - ./practice-7:/usr/share/nginx/html
    container_name: practice-7

  practice-8:
    build: .
    ports:
      - "8008:80"
    volumes:
      - ./practice-8:/usr/share/nginx/html
    container_name: practice-8

  practice-9:
    build: .
    ports:
      - "8009:80"
    volumes:
      - ./practice-9:/usr/share/nginx/html
    container_name: practice-9

  practice-10:
    build: .
    ports:
      - "8010:80"
    volumes:
      - ./practice-10:/usr/share/nginx/html
    container_name: practice-10

  practice-11:
    build: .
    ports:
      - "8011:80"
    volumes:
      - ./practice-11:/usr/share/nginx/html
    container_name: practice-11

  practice-12:
    build: .
    ports:
      - "8012:80"
    volumes:
      - ./practice-12:/usr/share/nginx/html
    container_name: practice-12

  practice-13:
    build: .
    ports:
      - "8013:80"
    volumes:
      - ./practice-13:/usr/share/nginx/html
    container_name: practice-13

  practice-14:
    build: .
    ports:
      - "8014:80"
    volumes:
      - ./practice-14:/usr/share/nginx/html
    container_name: practice-14

  practice-15:
    build: .
    ports:
      - "8015:80"
    volumes:
      - ./practice-15:/usr/share/nginx/html
    container_name: practice-15

  practice-16:
    build: .
    ports:
      - "8016:80"
    volumes:
      - ./practice-16:/usr/share/nginx/html
    container_name: practice-16

  practice-17:
    build: .
    ports:
      - "8017:80"
    volumes:
      - ./practice-17:/usr/share/nginx/html
    container_name: practice-17

  practice-18:
    build: .
    ports:
      - "8018:80"
    volumes:
      - ./practice-18:/usr/share/nginx/html
    container_name: practice-18

  practice-19:
    build: .
    ports:
      - "8019:80"
    volumes:
      - ./practice-19:/usr/share/nginx/html
    container_name: practice-19

  practice-20:
    build: .
    ports:
      - "8020:80"
    volumes:
      - ./practice-20:/usr/share/nginx/html
    container_name: practice-20
